# Generated by Django 3.0.6 on 2021-11-20 16:50

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(blank=True, choices=[('Mr', 'Sig'), ('Mrs', 'Signora'), ('Dott', 'Dottore'),
                                                                 ('Dott.ssa', 'Dottoressa'), ('Prof', 'Professore'),
                                                                 ('Prof.ssa', 'Professoressa')], max_length=20)),
                ('cognome', models.CharField(default='', help_text='Family name', max_length=60)),
                ('nome', models.CharField(default='', help_text='Name', max_length=60)),
                ('nascita', models.DateField(blank=True, default='1900-01-01', help_text='01/01/1988', null=True)),
                ('luogo_nascita', models.CharField(default='', max_length=100)),
                ('stato_nascita', models.CharField(default='', max_length=100)),
                ('genere',
                 models.CharField(choices=[('male', 'Maschio'), ('female', 'Femmina')], default='', max_length=10)),
                ('indirizzo', models.CharField(default='', max_length=100)),
                ('citta', models.CharField(default='', max_length=100)),
                ('provincia', models.CharField(default='', max_length=60)),
                ('stato', models.CharField(default='', max_length=60)),
                ('zip_code', models.CharField(default='', max_length=60)),
                ('telefono', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='',
                                                                            help_text='+393477093239 o 003321128832',
                                                                            max_length=128, null=True, region=None)),
                ('mobile', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='',
                                                                          help_text='+393477093239 o 003321128832',
                                                                          max_length=128, null=True, region=None)),
                ('mail', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('website',
                 models.CharField(blank=True, default='', help_text='sitoweb www', max_length=100, null=True)),
                ('lingua', models.CharField(
                    choices=[('IT - Italiano', 'Italiano'), ('EN - Inglese', 'Inglese'), ('FR - Francese', 'Francese'),
                             ('DE - Tedesco', 'Tedesco'), ('SP - Spagnolo', 'Spagnolo'),
                             ('PT - Portoghese', 'Portoghese')], default='IT', max_length=60)),
                ('imagefile',
                 models.ImageField(blank=True, db_column='imagefile', help_text='immagine autore se presente',
                                   upload_to='pic_folder/autori')),
            ],
            options={
                'verbose_name_plural': 'Autori',
            },
        ),
        migrations.CreateModel(
            name='Immagini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestamp', models.DateTimeField(auto_now_add=True)),
                ('commento', models.TextField(blank=True, default='', help_text="breve commento all'opera o note")),
                ('imagefile', models.ImageField(blank=True, db_column='imagefile', default='logo_no_image.png',
                                                upload_to='pic_folder/opere')),
                ('imagefile1', models.ImageField(blank=True, db_column='imagefile1', upload_to='pic_folder/opere/im1')),
                ('imagefile2', models.ImageField(blank=True, db_column='imagefile2', upload_to='pic_folder/opere/im2')),
                ('preview', models.ImageField(blank=True, db_column='preview', upload_to='pic_folder/opere/preview')),
                ('preview1',
                 models.ImageField(blank=True, db_column='preview1', upload_to='pic_folder/opere/preview1')),
                ('metainfo', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name_plural': 'Immagini',
            },
        ),
        migrations.CreateModel(
            name='Opera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo_opera', models.CharField(default='', max_length=400)),
                ('descrizione', models.TextField(blank=True, default='', null=True)),
                ('nazione', models.CharField(default='', max_length=60)),
                ('riconoscimenti', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('dimensione_lastra', models.CharField(default='', max_length=25)),
                ('dimensione_lastra_y', models.IntegerField(default=0, help_text='dimensione in mm')),
                ('dimensione_lastra_x', models.IntegerField(default=0, help_text='dimensione in mm')),
                ('dimensione_foglio_y', models.IntegerField(default=0, help_text='dimensione in mm')),
                ('dimensione_foglio_x', models.IntegerField(default=0, help_text='dimensione in mm')),
                ('tecnica', models.CharField(default='', max_length=500)),
                ('anno_realizzazione', models.IntegerField(default=2021)),
                ('edizione', models.TextField(blank=True, choices=[('XV Biennale - 2021', 'XV- Biennale -2021'),
                                                                   ('XIV Biennale - 2019', 'XIV- Biennale -2019'),
                                                                   ('XIII Biennale - 2017', 'XIII- Biennale -2017'),
                                                                   ('XII Biennale - 2015', 'XII- Biennale -2015'),
                                                                   ('XI Biennale - 2013', 'XI- Biennale -2013'),
                                                                   ('X Biennale - 2011', 'X- Biennale -2011'),
                                                                   ('IX Biennale - 2009', 'IX- Biennale -2009'),
                                                                   ('VIII Biennale - 2007', 'VIII- Biennale -2007'),
                                                                   ('VII Biennale - 2005', 'VII- Biennale -2005'),
                                                                   ('VI Biennale - 2003', 'VI- Biennale -2003'),
                                                                   ('V Biennale - 2001', 'V- Biennale -2001'),
                                                                   ('IV Biennale - 1999', 'IV- Biennale -1999'),
                                                                   ('III Biennale - 1997', 'III- Biennale -1997'),
                                                                   ('II Biennale - 1995', 'II- Biennale -1995'),
                                                                   ('I Biennale - 1993', 'I- Biennale -1993'),
                                                                   ('DA CANCELLARE', 'DA CANCELLARE')],
                                              default='XV Biennale - 2021', max_length=60)),
                ('note', models.TextField(blank=True, default='', max_length=500)),
                ('posizione_archivio', models.CharField(default='', max_length=60)),
                ('tag',
                 models.TextField(default='', help_text='inserire i tag separati da una virgola', max_length=200)),
                ('autore',
                 models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='autore',
                                   to='Gestionale.Autore')),
                ('immagini',
                 models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to='Gestionale.Immagini')),
            ],
            options={
                'verbose_name_plural': 'Opere',
            },
        ),
        migrations.AddField(
            model_name='immagini',
            name='titolo',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='img_titolo_opera', to='Gestionale.Opera'),
        ),
    ]
