# Generated by Django 3.2.9 on 2022-10-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opera',
            name='anno_realizzazione',
            field=models.IntegerField(default=2022),
        ),
        migrations.AlterField(
            model_name='opera',
            name='edizione',
            field=models.TextField(blank=True, choices=[('XVI Biennale - 2023', 'XVI- Biennale -2023'),
                                                        ('XV Biennale - 2021', 'XV- Biennale -2021'),
                                                        ('XIV Biennale - 2019', 'XIV- Biennale -2019'),
                                                        ('XIII Biennale - 2017', 'XIII- Biennale -2017'),
                                                        ('XII Biennale - 2015', 'XII- Biennale -2015'),
                                                        ('XI Biennale - 2013', 'XI- Biennale -2013'),
                                                        ('X Biennale - 2011', 'X- Biennale -2011'),
                                                        ('IX Biennale - 2009', 'IX- Biennale -2009'),
                                                        ('VIII Biennale - 2007', 'VIII- Biennale -2007'),
                                                        ('VII Biennale - 2005', 'VII- Biennale -2005'),
                                                        ('VI Biennale - 2003', 'VI- Biennale -2003'),
                                                        ('V Biennale - 2001', 'V- Biennale -2001'),
                                                        ('IV Biennale - 1999', 'IV- Biennale -1999'),
                                                        ('III Biennale - 1997', 'III- Biennale -1997'),
                                                        ('II Biennale - 1995', 'II- Biennale -1995'),
                                                        ('I Biennale - 1993', 'I- Biennale -1993'),
                                                        ('DA CANCELLARE', 'DA CANCELLARE'),
                                                        ('NON IN CONCORSO', 'NON IN CONCORSO')],
                                   default='XVI Biennale - 2023', max_length=60),
        ),
    ]
