# Generated by Django 3.2.9 on 2022-11-23 15:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0002_auto_20221002_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(unique=True)),
            ],
        ),
    ]
