# Generated by Django 3.2.9 on 2022-12-11 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0003_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='immagini',
            name='id_inventario',
            field=models.TextField(blank=True, default='-', help_text='Identificativo inventario'),
        ),
    ]
