# Generated by Django 3.2.9 on 2022-12-26 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0004_immagini_id_inventario'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='tags_s',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tag_s',
                                    to='Gestionale.tags'),
        ),
    ]
