# Generated by Django 3.2.9 on 2022-12-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0005_opera_tags_s'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opera',
            name='tags_s',
        ),
        migrations.AddField(
            model_name='opera',
            name='tags_s',
            field=models.ManyToManyField(null=True, related_name='tag_s', to='Gestionale.Tags'),
        ),
    ]
