# Generated by Django 3.2.9 on 2023-01-08 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0006_auto_20221226_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opera',
            name='anno_realizzazione',
            field=models.IntegerField(default=2023),
        ),
    ]
