# Generated by Django 3.2.9 on 2023-03-18 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0007_alter_opera_anno_realizzazione'),
    ]

    operations = [
        migrations.CreateModel(
            name='Localizzazione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('regione', models.TextField(blank=True, default='', null=True)),
                ('provincia', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('comune', models.CharField(blank=True, default='', max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'Localizzazioni',
            },
        ),
        migrations.CreateModel(
            name='LocalizzazioneSpecifica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia', models.CharField(blank=True, choices=[('Archivio', 'AR'), ('Raccolta', 'RA')], default='',
                                               max_length=30, null=True)),
                ('denominazione', models.TextField(blank=True, default='', null=True)),
                ('spazio_viabilistico', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('denominazione_raccolta', models.CharField(blank=True, default='', max_length=60, null=True)),
                ('specifiche', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('localizzazione', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                                     related_name='localizzazione', to='Gestionale.localizzazione')),
            ],
            options={
                'verbose_name_plural': 'Localizzazioni Specifiche',
            },
        ),
    ]
