# Generated by Django 3.2.9 on 2023-03-18 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0008_localizzazione_localizzazionespecifica'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='localizzazione',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                    related_name='Localizzazione', to='Gestionale.localizzazionespecifica'),
        ),
        migrations.AlterField(
            model_name='localizzazionespecifica',
            name='tipologia',
            field=models.CharField(blank=True, choices=[('AR', 'AR - Archivio'), ('RA', 'RA - Raccolta')], default='',
                                   max_length=30, null=True),
        ),
    ]
