# Generated by Django 3.2.9 on 2023-03-18 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0009_auto_20230318_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='identificazione',
            field=models.CharField(blank=True, default='', help_text='Es. serie di incisioni 1/7...', max_length=400,
                                   null=True),
        ),
        migrations.AddField(
            model_name='opera',
            name='quantita',
            field=models.CharField(blank=True, default='', help_text='Numero di copie presenti', max_length=10,
                                   null=True),
        ),
    ]
