# Generated by Django 3.2.9 on 2023-03-18 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0010_auto_20230318_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='definizione',
            field=models.CharField(choices=[('Matrice', 'Matrice'), ('Stampa', 'Stampa')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='opera',
            name='titolo_opera',
            field=models.CharField(blank=True, default='', max_length=400, null=True),
        ),
    ]
