# Generated by Django 3.2.9 on 2023-03-18 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0011_auto_20230318_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='identificazione_opera',
            field=models.TextField(blank=True, default='', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='opera',
            name='anno_realizzazione',
            field=models.IntegerField(blank=True, default=2023),
        ),
        migrations.AlterField(
            model_name='opera',
            name='localizzazione',
            field=models.ForeignKey(blank=True, help_text='Collocazione specifica', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='Localizzazione',
                                    to='Gestionale.localizzazionespecifica'),
        ),
        migrations.AlterField(
            model_name='opera',
            name='tags_s',
            field=models.ManyToManyField(help_text="Parole chiave che identificano il contenuto dell'opera", null=True,
                                         related_name='tag_s', to='Gestionale.Tags'),
        ),
    ]
