# Generated by Django 3.2.9 on 2023-03-18 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0012_auto_20230318_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='materia_lastra',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opera',
            name='motivazione_attribuzione',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opera',
            name='spessore_lastra',
            field=models.CharField(blank=True, default='', help_text='dimensione in mm', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='opera',
            name='tecnica_lastra',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opera',
            name='anno_realizzazione',
            field=models.IntegerField(blank=True, default=2023, help_text="Anno di creazione dell'opera"),
        ),
        migrations.AlterField(
            model_name='opera',
            name='autore',
            field=models.ForeignKey(blank=True,
                                    help_text="Indicazione dei dati anagrafici dell'autore. Se l'autore è presente in anagrafica fare una ricerca cliccando sulla prima lente di ingrandimento",
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='autore',
                                    to='Gestionale.autore'),
        ),
        migrations.AlterField(
            model_name='opera',
            name='dimensione_lastra_x',
            field=models.IntegerField(blank=True, default=0, help_text='dimensione in mm', null=True),
        ),
        migrations.AlterField(
            model_name='opera',
            name='dimensione_lastra_y',
            field=models.IntegerField(blank=True, default=0, help_text='dimensione in mm', null=True),
        ),
        migrations.AlterField(
            model_name='opera',
            name='edizione',
            field=models.TextField(blank=True, choices=[('XVI Biennale - 2023', 'XVI- Biennale -2023'),
                                                        ('XV Biennale - 2021', 'XV- Biennale -2021'),
                                                        ('XIV Biennale - 2019', 'XIV- Biennale -2019'),
                                                        ('XIII Biennale - 2017', 'XIII- Biennale -2017'),
                                                        ('XII Biennale - 2015', 'XII- Biennale -2015'),
                                                        ('XI Biennale - 2013', 'XI- Biennale -2013'),
                                                        ('X Biennale - 2011', 'X- Biennale -2011'),
                                                        ('IX Biennale - 2009', 'IX- Biennale -2009'),
                                                        ('VIII Biennale - 2007', 'VIII- Biennale -2007'),
                                                        ('VII Biennale - 2005', 'VII- Biennale -2005'),
                                                        ('VI Biennale - 2003', 'VI- Biennale -2003'),
                                                        ('V Biennale - 2001', 'V- Biennale -2001'),
                                                        ('IV Biennale - 1999', 'IV- Biennale -1999'),
                                                        ('III Biennale - 1997', 'III- Biennale -1997'),
                                                        ('II Biennale - 1995', 'II- Biennale -1995'),
                                                        ('I Biennale - 1993', 'I- Biennale -1993'),
                                                        ('DA CANCELLARE', 'DA CANCELLARE'),
                                                        ('NON IN CONCORSO', 'NON IN CONCORSO')],
                                   default='XVI Biennale - 2023',
                                   help_text="Edizione nella quale ha partecipato l'opera", max_length=60),
        ),
    ]
