# Generated by Django 3.2.9 on 2023-03-18 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0013_auto_20230318_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='formato_lastra',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
