# Generated by Django 3.2.9 on 2023-03-18 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0014_opera_formato_lastra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opera',
            name='dimensione_lastra',
        ),
        migrations.AddField(
            model_name='opera',
            name='formato_foglio',
            field=models.CharField(blank=True, default='', help_text='A4, 70x100...', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='opera',
            name='indicazioni_conservazione',
            field=models.TextField(blank=True, default='',
                                   help_text='Indicaizoni specifiche degli enentuali danni o parti rovinate nel dettaglio',
                                   max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='opera',
            name='materia_foglio',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opera',
            name='numero_lastre',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='opera',
            name='spessore_foglio',
            field=models.CharField(blank=True, default='', help_text='dimensione in mm', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='opera',
            name='stato_conservazione',
            field=models.CharField(blank=True, default='',
                                   help_text='Indicazione sintetica sullo stato di conservazione e se presenti parti rovinate',
                                   max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='opera',
            name='tecnica_foglio',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='opera',
            name='tecnica',
            field=models.CharField(blank=True, default='', help_text='non utilizzare - uso interno progrmma',
                                   max_length=500, null=True),
        ),
    ]
