# Generated by Django 3.2.9 on 2023-03-18 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0015_auto_20230318_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restauro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('situazione',
                 models.CharField(blank=True, default='', help_text="Stato dell'opera", max_length=300, null=True)),
                ('operatore', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('ente_responsabile', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Restauri',
            },
        ),
        migrations.AddField(
            model_name='opera',
            name='situazione_restauro',
            field=models.CharField(blank=True, default='', help_text="Stato dell'opera al momento del restauro",
                                   max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='opera',
            name='restauro',
            field=models.ForeignKey(blank=True, help_text='Se presente rastauro', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='Restauro',
                                    to='Gestionale.restauro'),
        ),
    ]
