# Generated by Django 3.2.9 on 2023-03-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0016_auto_20230318_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restauro',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
