# Generated by Django 3.2.9 on 2023-03-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0017_alter_restauro_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iscrizioni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_appartenenza',
                 models.TextField(blank=True, default='', help_text='Es. Celebrativa, commemorativa....', null=True)),
                ('lingua', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tecnica_scrittura', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tipo_caratteri', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('posizione', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('autore', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('trascrizione', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Iscrizioni',
            },
        ),
        migrations.CreateModel(
            name='DatiAnalitici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione',
                 models.TextField(blank=True, default='', help_text="Descrivi l'incisione con ordine", null=True)),
                ('iscrizioni', models.ManyToManyField(blank=True, default='', null=True, to='Gestionale.Iscrizioni')),
            ],
            options={
                'verbose_name_plural': 'Dati analitici',
            },
        ),
    ]
