# Generated by Django 3.2.9 on 2023-03-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0018_datianalitici_iscrizioni'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='dimensione_lastra',
            field=models.CharField(blank=True, default='', help_text='non utilizzare - uso interno progrmma',
                                   max_length=500, null=True),
        ),
    ]
