# Generated by Django 3.2.9 on 2023-03-18 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0019_opera_dimensione_lastra'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='dati_analitici',
            field=models.ForeignKey(blank=True, help_text="Dati analaitici per la descrizione dell'opera", null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='DatiAnalitici',
                                    to='Gestionale.datianalitici'),
        ),
        migrations.AddField(
            model_name='opera',
            name='notizie',
            field=models.TextField(blank=True, default='', help_text='Notizie storico-critiche-biogrfiche',
                                   max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='opera',
            name='descrizione',
            field=models.TextField(blank=True, default='', help_text="Descrivi l'incisione con ordine", null=True),
        ),
        migrations.AlterField(
            model_name='opera',
            name='nazione',
            field=models.CharField(blank=True, default='', help_text='Nazione provenienza opera', max_length=60,
                                   null=True),
        ),
    ]
