# Generated by Django 3.2.9 on 2023-03-18 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0020_auto_20230318_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='Giuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicazione_generica', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('indicazione_specifica', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('indirizzo', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tipo_provvedimento_tutela', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('estremi_provvedimento_tutela', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('data_notifica_provvedimento', models.DateField(blank=True, default='', null=True)),
            ],
            options={
                'verbose_name_plural': 'Giuridica',
            },
        ),
        migrations.AlterField(
            model_name='opera',
            name='nazione',
            field=models.CharField(blank=True, default='',
                                   help_text='Nazione provenienza opera, che potrebbe essere differente', max_length=60,
                                   null=True),
        ),
        migrations.AddField(
            model_name='opera',
            name='condizione_giuridica',
            field=models.ForeignKey(blank=True, help_text='Se presente vincolo o tutela', null=True,
                                    on_delete=django.db.models.deletion.DO_NOTHING, related_name='Giuridica',
                                    to='Gestionale.giuridica'),
        ),
    ]
