# Generated by Django 3.2.9 on 2023-03-18 18:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0021_auto_20230318_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='bibliografia',
            field=models.TextField(blank=True, default='',
                                   help_text='Indicaizoni di eventuali bibliograifie 1 per riga (Autore | Titolo | Anno edizione |pp. nn. figg. | Autore / AA.VV',
                                   null=True),
        ),
        migrations.AlterField(
            model_name='opera',
            name='notizie',
            field=models.TextField(blank=True, default='', help_text='Notizie storico-critiche-biogrfiche', null=True),
        ),
    ]
