# Generated by Django 3.2.9 on 2023-03-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0022_auto_20230318_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='mostre',
            field=models.TextField(blank=True, default='',
                                   help_text='Indicaizoni di eventuali mostre 1 per riga (Luogo | Titolo | Data',
                                   null=True),
        ),
    ]
