# Generated by Django 3.2.9 on 2023-03-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0023_opera_mostre'),
    ]

    operations = [
        migrations.AddField(
            model_name='opera',
            name='data_compilazione',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opera',
            name='data_ultimo_aggiornamento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opera',
            name='funzionario_responsabile',
            field=models.CharField(blank=True, default='', help_text='Cognome Nome', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='opera',
            name='nome_compilatore',
            field=models.CharField(blank=True, default='', help_text='Cognome Nome', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='opera',
            name='nome_revisore',
            field=models.CharField(blank=True, default='', help_text='Cognome Nome', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='opera',
            name='note',
            field=models.TextField(default='Osservazioni e annotazioni ulteriori', max_length=500),
        ),
        migrations.AlterField(
            model_name='opera',
            name='posizione_archivio',
            field=models.CharField(blank=True, default='',
                                   help_text='Codifica opere edizioni in coso, posizioni temporanee', max_length=60,
                                   null=True),
        ),
        migrations.AlterField(
            model_name='opera',
            name='tag',
            field=models.TextField(blank=True, default='',
                                   help_text='Da utilizzare per caricamento massivo di tag (devono essere in formato CSV)',
                                   max_length=200),
        ),
    ]
