# Generated by Django 3.2.9 on 2023-04-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0024_auto_20230318_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='autore',
            name='nascita_morte',
            field=models.DateField(blank=True, default='1900-01-01', help_text='01/01/1988', null=True),
        ),
    ]
