# Generated by Django 3.2.9 on 2023-04-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0026_auto_20230401_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autore',
            name='nascita_morte',
            field=models.DateField(blank=True, help_text='01/01/1988', null=True),
        ),
    ]
