# Generated by Django 3.2.9 on 2023-04-01 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0028_alter_autore_nascita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autore',
            name='nascita',
            field=models.DateField(blank=True, help_text='01/01/1988', null=True, verbose_name=['%Y-%m-%d']),
        ),
        migrations.AlterField(
            model_name='autore',
            name='nascita_morte',
            field=models.DateField(blank=True, help_text='01/01/1988', null=True, verbose_name=['%Y-%m-%d']),
        ),
    ]
