# Generated by Django 3.2.9 on 2023-04-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0029_auto_20230401_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autore',
            name='nascita',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autore',
            name='nascita_morte',
            field=models.DateField(blank=True, null=True),
        ),
    ]
