# Generated by Django 3.2.9 on 2023-04-01 16:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0030_auto_20230401_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autore',
            name='nascita_morte',
        ),
    ]
