# Generated by Django 3.2.9 on 2023-04-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0031_remove_autore_nascita_morte'),
    ]

    operations = [
        migrations.AddField(
            model_name='autore',
            name='nascita_morte',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='autore',
            name='nascita',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
