# Generated by Django 3.2.9 on 2023-04-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gestionale', '0032_auto_20230401_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autore',
            name='nascita',
            field=models.DateTimeField(blank=True, default='1900-01-01', null=True),
        ),
        migrations.AlterField(
            model_name='autore',
            name='nascita_morte',
            field=models.DateTimeField(blank=True, default='1900-01-01', null=True),
        ),
    ]
